apiVersion: v2
name: shenyu
description: Helm Chart for deploying Apache ShenYu in Kubernetes
type: application
version: 0.6.2
appVersion: "2.5.1"
icon: https://shenyu.apache.org/img/logo.png
maintainers:
  - name: erdengk
    email: wannengdek@gmail.com
  - name: aFlyBird0
    email: aflybird0@gmail.com
dependencies:
  - name: common
    version: 1.x.x
    repository: https://charts.bitnami.com/bitnami
