{{- if .Values.admin.enabled -}}
{{- if .Values.dataSource.mysql.enabled -}}
kind: Service
apiVersion: v1
metadata:
  name: {{ template "shenyu.fullname" . }}-mysql
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - port: 3306
    name: mysql
    targetPort: {{ required "database.mysql.port is required" .Values.dataSource.mysql.port }}
---
kind: Endpoints
apiVersion: v1
metadata:
  name: {{ template "shenyu.fullname" . }}-mysql
  namespace: {{ .Release.Namespace }}
subsets:
- addresses:
  - ip: {{ required "database.mysql.ip is required" .Values.dataSource.mysql.ip }}
  ports:
  - port: {{ required "database.mysql.port is required" .Values.dataSource.mysql.port }}
    name: mysql
{{- end -}}
{{- end -}}
