# 示例使用 nodeport 方式暴露端口
apiVersion: v1
kind: Service
metadata:
  namespace: {{.Release.Namespace}}
  name: shenyu-admin-svc
spec:
  selector:
    app: shenyu-admin
  type: NodePort
  ports:
    - protocol: TCP
      port: 9095
      targetPort: 9095
      nodePort: 31095
